### ISSUE TITLE
pm hide在adb下可用，在应用程序里面执行还是需要root权限

### ISSUE THREAD

**Issue by YiuChoi** [blackbbc/Evil-Hide#3]

**Comment by blackbbc** [comment]
咦 是吗
可是在adb下不需要root权限 好奇怪
怪不得我在程序里面用普通权限运行没有用

**Comment by wenmin-wu** [comment]
@blackbbc 我在程序中运行，抛出错误如下

```
java.lang.SecurityException: Neither user 10127 nor current process has android.permission.MANAGE_USERS.
                                           at android.os.Parcel.readException(Parcel.java:1620)
                                           at android.os.Parcel.readException(Parcel.java:1573)
                                           at android.content.pm.IPackageManager$Stub$Proxy.setApplicationHiddenSettingAsUser(IPackageManager.java:4979)
                                           at com.android.commands.pm.Pm.runSetHiddenSetting(Pm.java:1751)
                                           at com.android.commands.pm.Pm.run(Pm.java:198)
                                           at com.android.commands.pm.Pm.main(Pm.java:108)
                                           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                           at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
```

我对这个应用特别感兴趣，想和你一起优化它，给你发邮件了，方便的话加个微信一起讨论。我现在也在上海^_^
